### ISSUE TITLE
Problem with very large file size

### ISSUE THREAD

**Issue by SoftTools59654** [tableflowhq/tableflow#196]
Problem with very large file size

Do you have a way to import files of several million records with volumes of more than 10 gigs?

**Comment by ciminelli** [comment]
Hey @SoftTools59654 the frontend limits the upload to 1GB, but you can update this here: https://github.com/tableflowhq/tableflow/blob/9f0f80f242d88f5b03af3a71fb8ead8f0eb6a03a/importer-ui/src/components/UppyWrapper/index.tsx#L14

The backend can handle larger files but you might want to consider deploying a separate Scylla cluster rather than using the one in Docker if you need to consistently handle very large files.
